# Nome da aplicação
spring.application.name=api

# ===============================================
# 🔗 CONFIGURAÇÃO DO BANCO DE DADOS (PostgreSQL)
# ===============================================

# ❌ ERRADO para Docker: 'localhost' aponta para o próprio container Java
# spring.datasource.url=jdbc:postgresql://localhost:5432/api_java_topicos

# ✅ CORRETO: usar o nome do serviço declarado no docker-compose (db_postgres)
spring.datasource.url=jdbc:postgresql://db_postgres:5432/api_java_topicos
spring.datasource.username=daniel1
spring.datasource.password=daniel

# Driver JDBC para PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialeto do Hibernate para PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Mostrar SQL gerado no console
spring.jpa.show-sql=true

# Atualiza o schema do banco automaticamente
spring.jpa.hibernate.ddl-auto=update

# Configurações extras
spring.sql.init.mode=always
spring.sql.init.platform=postgresql
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.open-in-view=false

#CONFIGURAÇÃO DE AUTENTICAÇÃO JWT
jwt_secret=QWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXo=
jwt_expires=36000

# Caminho da documentação gerada pelo springdoc-openapi
springdoc.api-docs.path=/v3/api-docs

# Caminho base dos assets dos WebJars usados pelo Swagger UI
springdoc.swagger-ui.webjars.prefix=/webjars/

# Caminho da documentação (sem necessidade de ?url=)
springdoc.swagger-ui.url=/v3/api-docs

aws.cognito.region=
aws.cognito.url=
aws.cognito.userPoolId=
aws.cognito.clientId=
aws.cognito.clientSecret=

#rabbi
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Nome da fila que será consumida
rabbitmq.queue=user-created

# Nome da exchange usada para rotear mensagens
rabbitmq.exchange=user.exchange

# Routing key usada para direcionar mensagens
rabbitmq.routing-key=user-created
